Add Visual Alert Builder demo
microsoft/Cognitive-Samples-IntelligentKiosk pull request #81
Opened 2019-09-21 00:07 UTC by AlbertDavletov

2019-09-23 22:00 UTC, CarlosP-MS requested changes

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Views/VisualAlert/CustomVisionServiceWrapper.cs
> +        public async Task AddTrainingImagesAsync(IEnumerable<ImageAnalyzer> images, Guid modelId, Tag tag = null)
projectId

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Controls/LifecycleControl.xaml.cs
> +        public bool IsLatest { get; set; } = false;
It looks like this should be IsLast

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Controls/LifecycleControl.xaml.cs
> +        public string Title { get => title; set => Set(ref title, value); }
Is there a reason for doing it this way, instead of how you are doing with the Id property (e.g. public string Title {get; set; })? 

Same question for Subtitle and State.

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Views/VisualAlert/VisualAlertBuilderPage.xaml.cs
> +                    Title = isSingleScenario ? "Delete alert permanently?" : "Delete alerts permanently?",
Just make these written in a way that works for both.
Title: "Delete selected alert(s) permanently?"
Content: "This operation will delete the selected alert(s) permanently. Are you sure you want to continue?"

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Views/VisualAlert/VisualAlertBuilderPage.xaml.cs
> +        private void UpdateLeftPanel(BuilderMode mode = BuilderMode.ScenarioList)
UpdateScenarioListPanel

2019-09-23 22:00 UTC, CarlosP-MS commented on README.md
> +| [Visual Alert Builder](Documentation/VisualAlertBuilder.md)          | Shows how to use Custom Vision Service to quickly create an image classifier to detect visual states, and how to process frame
Let's add "Windows Machine Learning" next to "Custom Vision API" as an area, like we do for the Realtime Image Classification row.

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Controls/CameraControl.xaml.cs
> +        public int Count { get; set; }
CountdownValue

2019-09-23 22:00 UTC, CarlosP-MS commented on Kiosk/Controls/CameraControl.xaml.cs
> +                this.continuousModeGrid.Visibility = this.enableContinuousMode ? Visibility.Visible : Visibility.Collapsed;
Let's use data binding and do this in XAML instead. It will require adding propertychanged events, but that is the clearer.

Also, please confirm that the grid with the continuous mode button will not be visible unless this variable is set (e.g. it doesn't show up in some of the other demos that enable the camera buttons, but does show up in this new demo).

2019-09-24 00:43 UTC, AlbertDavletov commented on Kiosk/Controls/LifecycleControl.xaml.cs
> +        public string Title { get => title; set => Set(ref title, value); }
The "Set" func is defined in the BaseViewModel class which uses propertychanged event. I need to dynamically change some fields in this class (Title, Subtitle and State).
The "Id" property I define only at creation. Theoretically, we don't need to change it as well as IsLast field.

2019-09-24 02:34 UTC, AlbertDavletov commented on Kiosk/Controls/LifecycleControl.xaml.cs
> +        public bool IsLatest { get; set; } = false;
Fixed.

2019-09-24 02:34 UTC, AlbertDavletov commented on Kiosk/Views/VisualAlert/VisualAlertBuilderPage.xaml.cs
> +                    Title = isSingleScenario ? "Delete alert permanently?" : "Delete alerts permanently?",
Fixed.

2019-09-24 02:34 UTC, AlbertDavletov commented on Kiosk/Views/VisualAlert/VisualAlertBuilderPage.xaml.cs
> +        private void UpdateLeftPanel(BuilderMode mode = BuilderMode.ScenarioList)
Fixed.

2019-09-24 02:34 UTC, AlbertDavletov commented on README.md
> +| [Visual Alert Builder](Documentation/VisualAlertBuilder.md)          | Shows how to use Custom Vision Service to quickly create an image classifier to detect visual states, and how to process frame
Fixed.

2019-09-24 02:34 UTC, AlbertDavletov commented on Kiosk/Controls/CameraControl.xaml.cs
> +        public int Count { get; set; }
Fixed.

2019-09-24 02:35 UTC, AlbertDavletov commented on Kiosk/Controls/CameraControl.xaml.cs
> +                this.continuousModeGrid.Visibility = this.enableContinuousMode ? Visibility.Visible : Visibility.Collapsed;
Fixed.

2019-09-24 16:17 UTC, merged